<?xml version="1.0" encoding="UTF-8"?>
<simconf>
  <simulation>
    <title>Sim_45_RPL</title>
    <randomseed>527146</randomseed>
    <motetype>
      <identifier>z1</identifier>
      <description>z1</description>
      <source>[CONTIKI_DIR]/../build/udp-client_RPLCB.sky</source>
      <commands></commands>
    </motetype>
    
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>52</x>
        <y>181</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>1</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>194</x>
        <y>145</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>2</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>186</x>
        <y>76</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>3</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>83</x>
        <y>180</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>4</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>123</x>
        <y>14</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>5</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>51</x>
        <y>114</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>6</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>15</x>
        <y>96</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>7</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>126</x>
        <y>26</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>8</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>139</x>
        <y>183</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>9</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>31</x>
        <y>160</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>10</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>78</x>
        <y>171</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>11</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>129</x>
        <y>89</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>12</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>8</x>
        <y>1</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>13</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>49</x>
        <y>75</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>14</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>34</x>
        <y>187</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>15</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>96</x>
        <y>7</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>16</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>167</x>
        <y>89</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>17</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>179</x>
        <y>116</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>18</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>35</x>
        <y>180</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>19</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>72</x>
        <y>58</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>20</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>64</x>
        <y>172</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>21</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>13</x>
        <y>35</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>22</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>9</x>
        <y>28</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>23</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>62</x>
        <y>155</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>24</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>119</x>
        <y>195</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>25</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>42</x>
        <y>181</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>26</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>137</x>
        <y>90</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>27</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>156</x>
        <y>33</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>28</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>57</x>
        <y>147</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>29</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>115</x>
        <y>129</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>30</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>145</x>
        <y>136</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>31</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>8</x>
        <y>49</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>32</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>161</x>
        <y>165</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>33</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>14</x>
        <y>161</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>34</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>56</x>
        <y>86</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>35</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>186</x>
        <y>104</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>36</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>54</x>
        <y>150</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>37</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>59</x>
        <y>34</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>38</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>133</x>
        <y>8</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>39</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>65</x>
        <y>131</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>40</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>136</x>
        <y>68</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>41</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>8</x>
        <y>44</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>42</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>54</x>
        <y>196</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>43</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>139</x>
        <y>13</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>44</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>125</x>
        <y>167</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>45</node_id>
    </node>
  </simulation>
</simconf>
