<?xml version="1.0" encoding="UTF-8"?>
<simconf>
  <simulation>
    <title>Sim_70_RPL</title>
    <randomseed>407156</randomseed>
    <motetype>
      <identifier>z1</identifier>
      <description>z1</description>
      <source>[CONTIKI_DIR]/../build/udp-client_RPLCB.sky</source>
      <commands></commands>
    </motetype>
    
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>65</x>
        <y>124</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>1</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>42</x>
        <y>105</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>2</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>97</x>
        <y>120</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>3</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>125</x>
        <y>125</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>4</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>44</x>
        <y>124</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>5</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>132</x>
        <y>52</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>6</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>37</x>
        <y>126</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>7</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>45</x>
        <y>139</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>8</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>103</x>
        <y>7</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>9</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>7</x>
        <y>92</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>10</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>72</x>
        <y>187</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>11</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>34</x>
        <y>63</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>12</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>192</x>
        <y>21</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>13</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>134</x>
        <y>187</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>14</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>160</x>
        <y>164</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>15</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>108</x>
        <y>102</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>16</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>126</x>
        <y>42</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>17</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>115</x>
        <y>65</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>18</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>125</x>
        <y>80</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>19</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>36</x>
        <y>101</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>20</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>41</x>
        <y>137</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>21</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>47</x>
        <y>167</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>22</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>175</x>
        <y>134</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>23</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>106</x>
        <y>56</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>24</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>57</x>
        <y>32</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>25</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>71</x>
        <y>194</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>26</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>42</x>
        <y>18</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>27</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>175</x>
        <y>22</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>28</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>16</x>
        <y>191</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>29</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>137</x>
        <y>9</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>30</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>123</x>
        <y>191</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>31</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>79</x>
        <y>91</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>32</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>9</x>
        <y>197</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>33</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>29</x>
        <y>161</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>34</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>57</x>
        <y>89</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>35</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>51</x>
        <y>187</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>36</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>51</x>
        <y>173</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>37</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>107</x>
        <y>85</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>38</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>125</x>
        <y>14</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>39</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>45</x>
        <y>167</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>40</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>85</x>
        <y>109</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>41</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>36</x>
        <y>51</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>42</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>80</x>
        <y>80</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>43</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>89</x>
        <y>76</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>44</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>196</x>
        <y>169</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>45</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>105</x>
        <y>163</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>46</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>158</x>
        <y>188</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>47</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>31</x>
        <y>176</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>48</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>133</x>
        <y>80</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>49</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>127</x>
        <y>115</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>50</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>56</x>
        <y>60</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>51</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>46</x>
        <y>72</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>52</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>105</x>
        <y>124</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>53</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>156</x>
        <y>187</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>54</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>46</x>
        <y>120</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>55</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>73</x>
        <y>17</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>56</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>49</x>
        <y>182</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>57</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>157</x>
        <y>40</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>58</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>118</x>
        <y>60</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>59</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>132</x>
        <y>153</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>60</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>3</x>
        <y>36</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>61</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>171</x>
        <y>33</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>62</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>35</x>
        <y>48</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>63</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>73</x>
        <y>69</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>64</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>197</x>
        <y>118</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>65</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>185</x>
        <y>136</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>66</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>51</x>
        <y>112</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>67</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>125</x>
        <y>80</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>68</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>184</x>
        <y>36</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>69</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>85</x>
        <y>189</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>70</node_id>
    </node>
  </simulation>
</simconf>
