<?xml version="1.0" encoding="UTF-8"?>
<simconf>
  <simulation>
    <title>Sim_55_RPL</title>
    <randomseed>423673</randomseed>
    <motetype>
      <identifier>z1</identifier>
      <description>z1</description>
      <source>[CONTIKI_DIR]/../build/udp-client_RPLCB.sky</source>
      <commands></commands>
    </motetype>
    
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>170</x>
        <y>175</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>1</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>178</x>
        <y>78</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>2</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>52</x>
        <y>91</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>3</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>198</x>
        <y>33</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>4</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>196</x>
        <y>54</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>5</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>180</x>
        <y>21</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>6</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>34</x>
        <y>141</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>7</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>90</x>
        <y>44</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>8</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>166</x>
        <y>106</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>9</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>67</x>
        <y>156</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>10</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>92</x>
        <y>1</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>11</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>115</x>
        <y>64</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>12</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>124</x>
        <y>13</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>13</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>112</x>
        <y>136</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>14</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>171</x>
        <y>85</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>15</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>181</x>
        <y>140</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>16</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>12</x>
        <y>75</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>17</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>164</x>
        <y>176</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>18</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>200</x>
        <y>177</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>19</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>4</x>
        <y>51</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>20</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>76</x>
        <y>30</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>21</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>19</x>
        <y>80</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>22</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>150</x>
        <y>78</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>23</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>16</x>
        <y>174</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>24</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>32</x>
        <y>11</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>25</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>130</x>
        <y>108</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>26</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>49</x>
        <y>35</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>27</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>104</x>
        <y>189</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>28</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>126</x>
        <y>14</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>29</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>195</x>
        <y>154</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>30</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>58</x>
        <y>88</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>31</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>164</x>
        <y>97</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>32</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>143</x>
        <y>57</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>33</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>79</x>
        <y>198</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>34</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>31</x>
        <y>33</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>35</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>178</x>
        <y>55</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>36</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>69</x>
        <y>24</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>37</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>112</x>
        <y>11</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>38</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>132</x>
        <y>53</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>39</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>7</x>
        <y>42</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>40</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>101</x>
        <y>192</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>41</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>22</x>
        <y>114</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>42</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>80</x>
        <y>17</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>43</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>83</x>
        <y>5</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>44</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>59</x>
        <y>152</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>45</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>103</x>
        <y>137</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>46</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>9</x>
        <y>189</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>47</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>73</x>
        <y>178</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>48</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>96</x>
        <y>131</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>49</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>43</x>
        <y>97</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>50</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>7</x>
        <y>128</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>51</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>146</x>
        <y>164</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>52</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>93</x>
        <y>134</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>53</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>176</x>
        <y>128</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>54</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>92</x>
        <y>18</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>55</node_id>
    </node>
  </simulation>
</simconf>
