<?xml version="1.0" encoding="UTF-8"?>
<simconf>
  <simulation>
    <title>Sim_65_RPL</title>
    <randomseed>356623</randomseed>
    <motetype>
      <identifier>z1</identifier>
      <description>z1</description>
      <source>[CONTIKI_DIR]/../build/udp-client_RPLCB.sky</source>
      <commands></commands>
    </motetype>
    
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>187</x>
        <y>169</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>1</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>194</x>
        <y>175</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>2</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>90</x>
        <y>190</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>3</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>177</x>
        <y>3</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>4</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>169</x>
        <y>13</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>5</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>107</x>
        <y>10</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>6</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>137</x>
        <y>44</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>7</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>21</x>
        <y>67</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>8</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>22</x>
        <y>172</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>9</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>182</x>
        <y>14</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>10</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>172</x>
        <y>60</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>11</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>1</x>
        <y>37</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>12</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>97</x>
        <y>6</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>13</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>117</x>
        <y>167</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>14</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>55</x>
        <y>198</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>15</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>172</x>
        <y>165</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>16</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>185</x>
        <y>183</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>17</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>135</x>
        <y>1</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>18</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>47</x>
        <y>135</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>19</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>193</x>
        <y>53</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>20</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>76</x>
        <y>8</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>21</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>59</x>
        <y>12</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>22</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>31</x>
        <y>165</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>23</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>61</x>
        <y>8</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>24</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>158</x>
        <y>56</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>25</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>58</x>
        <y>59</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>26</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>72</x>
        <y>65</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>27</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>93</x>
        <y>139</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>28</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>68</x>
        <y>134</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>29</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>149</x>
        <y>64</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>30</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>184</x>
        <y>102</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>31</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>46</x>
        <y>85</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>32</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>43</x>
        <y>194</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>33</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>179</x>
        <y>125</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>34</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>40</x>
        <y>64</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>35</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>46</x>
        <y>86</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>36</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>8</x>
        <y>116</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>37</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>18</x>
        <y>75</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>38</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>178</x>
        <y>53</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>39</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>68</x>
        <y>63</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>40</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>46</x>
        <y>125</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>41</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>96</x>
        <y>145</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>42</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>112</x>
        <y>13</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>43</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>104</x>
        <y>161</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>44</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>96</x>
        <y>160</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>45</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>165</x>
        <y>133</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>46</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>161</x>
        <y>130</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>47</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>19</x>
        <y>174</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>48</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>154</x>
        <y>173</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>49</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>164</x>
        <y>151</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>50</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>48</x>
        <y>60</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>51</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>47</x>
        <y>160</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>52</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>127</x>
        <y>100</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>53</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>168</x>
        <y>75</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>54</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>100</x>
        <y>8</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>55</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>114</x>
        <y>86</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>56</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>120</x>
        <y>164</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>57</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>120</x>
        <y>135</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>58</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>29</x>
        <y>36</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>59</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>35</x>
        <y>178</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>60</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>9</x>
        <y>96</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>61</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>88</x>
        <y>86</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>62</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>200</x>
        <y>168</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>63</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>0</x>
        <y>142</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>64</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>42</x>
        <y>47</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>65</node_id>
    </node>
  </simulation>
</simconf>
