<?xml version="1.0" encoding="UTF-8"?>
<simconf>
  <simulation>
    <title>Sim_30_RPL</title>
    <randomseed>901800</randomseed>
    <motetype>
      <identifier>z1</identifier>
      <description>z1</description>
      <source>[CONTIKI_DIR]/../build/udp-client_RPLCB.sky</source>
      <commands></commands>
    </motetype>
    
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>191</x>
        <y>87</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>1</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>1</x>
        <y>96</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>2</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>194</x>
        <y>150</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>3</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>108</x>
        <y>152</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>4</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>7</x>
        <y>87</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>5</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>7</x>
        <y>148</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>6</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>177</x>
        <y>126</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>7</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>15</x>
        <y>116</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>8</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>195</x>
        <y>118</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>9</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>34</x>
        <y>148</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>10</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>105</x>
        <y>3</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>11</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>38</x>
        <y>170</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>12</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>139</x>
        <y>139</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>13</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>37</x>
        <y>30</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>14</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>5</x>
        <y>144</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>15</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>126</x>
        <y>161</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>16</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>96</x>
        <y>107</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>17</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>124</x>
        <y>83</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>18</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>75</x>
        <y>121</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>19</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>29</x>
        <y>46</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>20</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>147</x>
        <y>31</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>21</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>161</x>
        <y>139</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>22</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>9</x>
        <y>177</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>23</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>48</x>
        <y>112</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>24</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>20</x>
        <y>11</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>25</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>55</x>
        <y>7</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>26</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>47</x>
        <y>54</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>27</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>107</x>
        <y>198</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>28</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>183</x>
        <y>114</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>29</node_id>
    </node>
    <node>
      <breakpoints></breakpoints>
      <interface_config>
        <interface>org.contikios.cooja.interfaces.Position</interface>
        <x>2</x>
        <y>110</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>z1</motetype_identifier>
      <node_id>30</node_id>
    </node>
  </simulation>
</simconf>
