#ifndef PROJECT_CONF_H_
#define PROJECT_CONF_H_

#define UIP_MAX_ROUTES 20
#define NBR_TABLE_CONF_MAX_NEIGHBORS 20
#define RPL_CONF_MOP RPL_MOP_NON_STORING
#define RPL_CONF_DEFAULT_LIFETIME_UNIT 60
#define RPL_CONF_DEFAULT_LIFETIME 10

#define INITIAL_ENERGY_mJ 8800

#endif /* PROJECT_CONF_H_ */
